default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: railsuser
  password: railsuser

development:
  <<: *default
  database: ProdRevCenterMail_development

test:
  <<: *default
  database: ProdRevCenterMail_test

production:
  <<: *default
  database: ProdRevCenterMail_production
  username: ProdRevCenterMail
  password: <%= ENV['PRODREVCENTERMAIL_DATABASE_PASSWORD'] %>
